apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:
  name: postgres-storage  
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 100Mi  
---
apiVersion: apps/v1  
kind: Deployment  
metadata:
  name: postgres 
  labels:
    app: postgres
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      containers:
      - name: postgres  
        image: postgres:15
        ports:
        - containerPort: 5432
        env:  
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets 
              key: POSTGRES_USER 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets  
              key: POSTGRES_PASSWORD  
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configs  
              key: POSTGRES_DB

        volumeMounts:
        - name: postgres-storage  
          mountPath: /var/lib/postgresql/data  
      volumes:  
      - name: postgres-storage 
        persistentVolumeClaim:
          claimName: postgres-storage  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service  
  labels:
    app: postgres  
spec:
  type: ClusterIP  
  ports:
  - port: 5432  
    targetPort: 5432  
  selector:
    app: postgres  
